version: '3'

tasks:

  cecil:start:
    desc: Start Cecil local server and watcher.
    cmds:
      - php cecil.phar serve
    aliases: [start]

  cecil:build:
    desc: Builds the website.
    cmds:
      - rm -rf ./.cache/*
      - rm -rf ./_site/*
      - php cecil.phar build
    aliases: [build]

  deploy:production:
    cmds:
      - task: cecil:build
      - rsync -atvPI ./_site/ xxx:/opt/zllr-web-prd/web
    aliases: [deploy]